version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  web:
    build:
      context: ./docker/web
    volumes:
      - ./:/var/www:cached
      - ./docker/web/logs/:/var/log/nginx
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8083:80"
      - "4433:443"
    links:
      - "db:db_host"

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: UTC
    ports:
      - "${LOCAL_DB_PORT}:3306"
    networks:
      - backend
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/setup.sql:/docker-entrypoint-initdb.d/0_init.sql

  workspace:
    build:
      context: ./docker/workspace
      args:
        - PHP_VERSION=7.4
        - INSTALL_XDEBUG=false
        - INSTALL_PHPREDIS=true
        - INSTALL_NODE=true
        - NPM_REGISTRY=
        - INSTALL_YARN=false
        - COMPOSER_GLOBAL_INSTALL=true
        - COMPOSER_REPO_PACKAGIST=
        - INSTALL_WORKSPACE_SSH=true
        - INSTALL_LARAVEL_INSTALLER=true
        - INSTALL_IMAGEMAGICK=false
        - INSTALL_DUSK_DEPS=false
        - INSTALL_PG_CLIENT=false
        - PUID=1000
        - PGID=1000
        - CHROME_DRIVER_VERSION=2.32
        - NODE_VERSION=stable
        - YARN_VERSION=latest
        - TZ=UTC

    volumes:
      - ./:/var/www:cached
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=laravel-docker

  php:
    image: alexkb/php-fpm-alpine-laravel
    volumes:
      - ./:/var/www:cached
    expose:
      - "9000"
    networks:
      - backend
    links:
      - "db:db_host"


